spring:
  application:
    name: PetCare
  datasource:
    url: jdbc:mysql://localhost:33060/petcare?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678a@
    driver-class-name: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      enabled: false
      lifecycle-management: start-only
      file: src/main/docker/services.yml
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: '@spring.profiles.active@'
    group:
      dev:
        - dev
        - api-docs
        # Uncomment to activate TLS for the dev profile
        #- tls
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  liquibase:
    enabled: false # nếu muốn tự Hibernate tạo bảng thì tắt Liquibase đi

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.petcare: DEBUG

jhipster:
  clientApp:
    name: 'petCareApp'
  api-docs:
    default-include-pattern: /api/**
    title: Pet Care API
    description: Pet Care API documentation
    version: 0.0.1
